# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION:  ${{ matrix.jdk }}

    steps:
    - uses: actions/checkout@v2
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew        
    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v4
      with:
        node-version: 8.12.0
    - name: Pre-generate API docs
      run: ./gradlew classes testClasses -x generateApiDocs
    - name: Test WireMock
      run: ./gradlew check --stacktrace --no-daemon

    - name: Archive WireMock test report - Windows
      if: ${{ contains(matrix.os, 'windows') }}
      uses: actions/upload-artifact@v2
      with:
        name: wiremock-core-test-report-${{ matrix.os }}
        path: build\reports\tests
    - name: Archive Webhooks test report - Windows
      if: ${{ contains(matrix.os, 'windows') }}
      uses: actions/upload-artifact@v2
      with:
        name: wiremock-webhooks-extension-test-report-${{ matrix.os }}
        path: wiremock-webhooks-extension\build\reports\tests

    - name: Archive WireMock test report
      uses: actions/upload-artifact@v2
      with:
        name: wiremock-core-test-report-${{ matrix.os }}
        path: build/reports/tests
    - name: Archive Webhooks test report
      uses: actions/upload-artifact@v2
      with:
        name: wiremock-webhooks-extension-test-report-${{ matrix.os }}
        path: wiremock-webhooks-extension/build/reports/tests